/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CountryDataMaintainer;

import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business;
import model.Country.Country;
import model.DataAnalyze.MacroData;
import model.Role.DataMaintainerRole;
import model.Role.Role;
import model.UserAccount.UserAccount;

/**
 *
 * @author changxu
 */
public class CountryDataMaintainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CountryDataMaintainJPanel
     */
    
    JPanel userProcessContainer;
    UserAccount account;
    Business business;
    DataMaintainerRole role;
    Country country;
    
    public CountryDataMaintainJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.business = Business.getInstance();
        this.role = (DataMaintainerRole) account.getRole();
        this.country = account.getOrganization().getCountry();
        
        if(country != null){           
            lblCountry.setText(country.toString());
            refreshTable();
        }        
        
    }
    
    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel) tblYear.getModel();
        model.setRowCount(0);
        
        for(Integer year:country.getMacroDataMap().keySet()){
            Object[] row = new Object[1];
            MacroData md = country.getMacroDataMap().get(year);
            row[0] = md;
            model.addRow(row);            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logoAdd = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblYear = new javax.swing.JTable();
        logoView = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_vertical.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setText("Country Data Maintainer Work Area");

        logoAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-database-64.png"))); // NOI18N
        logoAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoAddMouseClicked(evt);
            }
        });

        lblAdd.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAdd.setText("Add New Annual Data");
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddMouseExited(evt);
            }
        });

        lblCountry.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCountry.setText("<Country Label>");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Country:");

        tblYear.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tblYear.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year"
            }
        ));
        jScrollPane1.setViewportView(tblYear);

        logoView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-view-50.png"))); // NOI18N
        logoView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoViewMouseClicked(evt);
            }
        });

        lblView.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblView.setText("View Annual Data");
        lblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdd)
                        .addGap(169, 169, 169)
                        .addComponent(logoView, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblView))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblCountry))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(bg))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCountry))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdd)
                            .addComponent(lblView))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoAddMouseClicked
        // TODO add your handling code here:
//        if(country == null){
//            JOptionPane.showMessageDialog(this, "Plese select a country first.");
//            return;
//        }
//        MaintainRegionalDataJPanel mrdj = (MaintainRegionalDataJPanel) new MaintainRegionalDataJPanel(userProcessContainer, country);
//        userProcessContainer.add("MaintainRegionalDataJPanel", mrdj);
//        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
//        crdLyt.next(userProcessContainer);                  

    }//GEN-LAST:event_logoAddMouseClicked

    private void logoViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoViewMouseClicked
        // TODO add your handling code here:
//        int selectedRow = tblYear.getSelectedRow();        
//        if (selectedRow < 0){
//            JOptionPane.showMessageDialog(this, "Please select a year.");
//            return;
//        }
//        
//        MacroData md = (MacroData) tblYear.getValueAt(selectedRow, 0);
//        ViewRegionalDataJPanel vrdj = (ViewRegionalDataJPanel) new ViewRegionalDataJPanel(userProcessContainer, md, country);
//        userProcessContainer.add("ViewRegionalDataJPanel", vrdj);
//        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
//        crdLyt.next(userProcessContainer);                          

    }//GEN-LAST:event_logoViewMouseClicked

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked
        // TODO add your handling code here:
        if(country == null){
            JOptionPane.showMessageDialog(this, "Plese select a country first.");
            return;
        }
        MaintainRegionalDataJPanel mrdj = (MaintainRegionalDataJPanel) new MaintainRegionalDataJPanel(userProcessContainer, country);
        userProcessContainer.add("MaintainRegionalDataJPanel", mrdj);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);                  
        
    }//GEN-LAST:event_lblAddMouseClicked

    private void lblAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseEntered
        // TODO add your handling code here:
        lblAdd.setFont(new Font("Lucida",  Font.BOLD, 18));
    }//GEN-LAST:event_lblAddMouseEntered

    private void lblAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseExited
        // TODO add your handling code here:
        lblAdd.setFont(new Font("Lucida",  Font.PLAIN, 18));
    }//GEN-LAST:event_lblAddMouseExited

    private void lblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblYear.getSelectedRow();        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select a year.");
            return;
        }
        
        MacroData md = (MacroData) tblYear.getValueAt(selectedRow, 0);
        ViewRegionalDataJPanel vrdj = (ViewRegionalDataJPanel) new ViewRegionalDataJPanel(userProcessContainer, md, country);
        userProcessContainer.add("ViewRegionalDataJPanel", vrdj);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);                          
        
    }//GEN-LAST:event_lblViewMouseClicked

    private void lblViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseEntered
        // TODO add your handling code here:
        lblView.setFont(new Font("Lucida",  Font.BOLD, 18));
    }//GEN-LAST:event_lblViewMouseEntered

    private void lblViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewMouseExited
        // TODO add your handling code here:
        lblView.setFont(new Font("Lucida",  Font.PLAIN, 18));
    }//GEN-LAST:event_lblViewMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblView;
    private javax.swing.JLabel logoAdd;
    private javax.swing.JLabel logoView;
    private javax.swing.JTable tblYear;
    // End of variables declaration//GEN-END:variables
}
