/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CountryDataMaintainer;

/**
 *
 * @author changxu
 */
public class MaintainRegionalDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaintainRegionalDataJPanel
     */
    public MaintainRegionalDataJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        signInLbl = new javax.swing.JLabel();
        signUpLbl = new javax.swing.JLabel();
        suLogo = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        usernameField = new javax.swing.JTextField();
        siLogo = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        signInLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        signInLbl.setText("Sign in");
        jLayeredPane1.add(signInLbl);
        signInLbl.setBounds(380, 660, 80, 22);

        signUpLbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        signUpLbl.setText("Sign up");
        jLayeredPane1.add(signUpLbl);
        signUpLbl.setBounds(210, 660, 80, 22);

        suLogo.setText("logo");
        jLayeredPane1.add(suLogo);
        suLogo.setBounds(150, 660, 50, 30);

        passwordLbl.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        passwordLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLbl.setText("Password");
        jLayeredPane1.add(passwordLbl);
        passwordLbl.setBounds(140, 570, 65, 22);

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jPasswordField);
        jPasswordField.setBounds(220, 560, 210, 40);

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        jLayeredPane1.add(usernameField);
        usernameField.setBounds(220, 500, 210, 40);

        siLogo.setText("logo");
        jLayeredPane1.add(siLogo);
        siLogo.setBounds(330, 650, 40, 40);

        name.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setText("Maintain Regional Data");
        jLayeredPane1.add(name);
        name.setBounds(60, 60, 320, 60);

        name1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        name1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name1.setText("Username");
        jLayeredPane1.add(name1);
        name1.setBounds(120, 510, 90, 17);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        bg.setText("jLabel1");
        jLayeredPane1.add(bg);
        bg.setBounds(0, 0, 1430, 890);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel siLogo;
    private javax.swing.JLabel signInLbl;
    private javax.swing.JLabel signUpLbl;
    private javax.swing.JLabel suLogo;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
