/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CharityFundingGroup;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Business;
import model.CharityFundingGroup.CharityFundingManager;
import model.UserAccount.UserAccount;

/**
 *
 * @author kkkkayla
 */
public class CharityFundingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharityFundingGroupLoginJPanel
     */
    
    
    JPanel userProcessContainer;
    Business business = Business.getInstance();
    CharityFundingManager fundGroup;
    UserAccount account;
    
    
    public CharityFundingWorkAreaJPanel(JPanel userProcessContainer,UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.fundGroup = new CharityFundingManager();
        this.fundGroup.setUsername(account.getUsername());
        //this.fundGroup = (CharityFundingManager)account;
        
        labelName.setText(fundGroup.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        lblfund = new javax.swing.JLabel();
        logoRequest1 = new javax.swing.JLabel();
        lblReq = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_vertical.png"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(1060, 0, 383, 900);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Charity Funding Group Work Area");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 1040, 90);

        labelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelName.setText("<value>");
        jPanel1.add(labelName);
        labelName.setBounds(299, 270, 150, 40);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Charity Funding Group:");
        jPanel1.add(enterpriseLabel);
        enterpriseLabel.setBounds(70, 280, 210, 22);

        lblfund.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblfund.setText("Manage Funding");
        lblfund.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfundMouseClicked(evt);
            }
        });
        jPanel1.add(lblfund);
        lblfund.setBounds(150, 400, 300, 22);

        logoRequest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-communicate-50.png"))); // NOI18N
        logoRequest1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoRequest1MouseClicked(evt);
            }
        });
        jPanel1.add(logoRequest1);
        logoRequest1.setBounds(80, 480, 50, 50);

        lblReq.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblReq.setText("Manage Request");
        lblReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReqMouseClicked(evt);
            }
        });
        jPanel1.add(lblReq);
        lblReq.setBounds(150, 500, 143, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-student-40.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 380, 60, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoRequest1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoRequest1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_logoRequest1MouseClicked

    private void lblfundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfundMouseClicked
        // TODO add your handling code here:
        ManageFundingJPanel mfjp = new ManageFundingJPanel(userProcessContainer, account, fundGroup);
        userProcessContainer.add(mfjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_lblfundMouseClicked

    private void lblReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReqMouseClicked
        // TODO add your handling code here:
        CharityFundGroupReqJPanel cfgrjp = new CharityFundGroupReqJPanel(userProcessContainer, account, business);
        userProcessContainer.add(cfgrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_lblReqMouseClicked

    
    private void back() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel lblReq;
    private javax.swing.JLabel lblfund;
    private javax.swing.JLabel logoRequest1;
    // End of variables declaration//GEN-END:variables
}
