/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CharityFundingGroup;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business;
import model.CharityFundingGroup.CharityFundingManager;
import model.Country.Country;
import model.Request.Request;
import model.UserAccount.UserAccount;

/**
 *
 * @author kkkkayla
 */
public class CharityFundGroupReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharityFundGroupJPanel
     */
    JPanel userProcessContainer;

    UserAccount userAccount;

    Business business;

    CharityFundingManager fundGroup;

    public CharityFundGroupReqJPanel(JPanel userProcessContainer, UserAccount account, Business system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = Business.getInstance();
        this.fundGroup = fundGroup;
        populateRequestTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFund = new javax.swing.JTable();
        lblWelcome = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        btnDeny = new javax.swing.JButton();
        btnAccept1 = new javax.swing.JButton();
        backLbl = new javax.swing.JLabel();
        btnViewSent = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tblFund.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Request Date", "Title", "Request Fund", "Status ", "Resolve Date"
            }
        ));
        jScrollPane1.setViewportView(tblFund);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 240, 820, 300);

        lblWelcome.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome Funding Group");
        lblWelcome.setToolTipText("");
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblWelcome);
        lblWelcome.setBounds(10, 110, 1050, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_vertical.png"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(1060, 0, 383, 900);

        btnDeny.setText("Reject");
        btnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeny);
        btnDeny.setBounds(740, 590, 170, 29);

        btnAccept1.setText("Accept");
        btnAccept1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccept1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccept1);
        btnAccept1.setBounds(410, 590, 170, 29);

        backLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-back-to-52.png"))); // NOI18N
        backLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLblMouseClicked(evt);
            }
        });
        jPanel1.add(backLbl);
        backLbl.setBounds(50, 40, 52, 52);

        btnViewSent.setText("View  ");
        btnViewSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSentActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewSent);
        btnViewSent.setBounds(90, 590, 150, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1433, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 875, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblFund.getModel();
        model.setRowCount(0);

        for (Country c : business.getCountryDirectory().getName2Country().values()) {
            for (Request r : c.getRequestList()) {

                Object[] row = new Object[6];
                //if(r.getResourceProvider().getName()== fundGroup.getOrganization().getName()){
                if (r.getRequestType() == Request.RequestType.FundRequest) {

                    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    row[0] = r.getSchool().getName();
                    row[1] = df.format(r.getRequestDate());
                    row[2] = r.getTitle();
                    //row[3] = r
                    row[4] = r.getRequestStatusType().toString();
                    row[5] = r.getResolveDate() == null ? "" : df.format(r.getResolveDate());
                    model.addRow(row);
                }
            }
        }
        //}
    }


    private void btnAccept1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccept1ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblFund.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblFund.getModel();
        Request selectedReq = (Request) model.getValueAt(selectedRowIndex, 0);
        selectedReq.setResolveDate(new Date());

        selectedReq.setRequestStatusType(Request.RequestStatusType.AcceptResourceProvider);

        populateRequestTable();
    }//GEN-LAST:event_btnAccept1ActionPerformed

    private void backLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLblMouseClicked
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_backLblMouseClicked

    private void btnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblFund.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request first.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblFund.getModel();
        Request selectedReq = (Request) model.getValueAt(selectedRowIndex, 0);
        selectedReq.setResolveDate(new Date());

        selectedReq.setRequestStatusType(Request.RequestStatusType.RejectResourceProvider);

        populateRequestTable();
    }//GEN-LAST:event_btnDenyActionPerformed

    private void btnViewSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSentActionPerformed
        // TODO add your handling code here:
        int indexRow = tblFund.getSelectedRow();
        if (indexRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to view.");
            return;
        }
        Request r = (Request) tblFund.getValueAt(indexRow, 2);
        ViewRequestJPanel vrjp = (ViewRequestJPanel) new ViewRequestJPanel(userProcessContainer, userAccount, r);
        userProcessContainer.add("ViewRequestJPanel", vrjp);
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_btnViewSentActionPerformed

    private void back() {
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLbl;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAccept1;
    private javax.swing.JButton btnDeny;
    private javax.swing.JButton btnViewSent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblFund;
    // End of variables declaration//GEN-END:variables
}
