/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CharityFundingGroup;

import javax.swing.JPanel;
import model.Business;
import model.CharityFundingGroup.CharityFundingGroup;
import model.UserAccount.UserAccount;

/**
 *
 * @author kkkkayla
 */
public class CharityFundingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CharityFundingGroupLoginJPanel
     */
    
    
    JPanel userProcessContainer;
    Business business;
    CharityFundingGroup fundGroup;
    
    
    public CharityFundingWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        btnManageReq = new javax.swing.JButton();
        btnManageClass1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_vertical.png"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(1060, 0, 383, 900);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Charity Funding Group Work Area");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 1040, 90);

        labelName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelName.setText("<value>");
        jPanel1.add(labelName);
        labelName.setBounds(270, 270, 79, 40);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Charity Funding Group:");
        jPanel1.add(enterpriseLabel);
        enterpriseLabel.setBounds(20, 280, 210, 22);

        btnManageReq.setText("Manage Request");
        btnManageReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReqActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageReq);
        btnManageReq.setBounds(250, 550, 400, 29);

        btnManageClass1.setText("Manage Funding ");
        btnManageClass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageClass1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageClass1);
        btnManageClass1.setBounds(250, 450, 400, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1437, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageReqActionPerformed

    private void btnManageClass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageClass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageClass1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnManageClass1;
    private javax.swing.JButton btnManageReq;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelName;
    // End of variables declaration//GEN-END:variables
}
