/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EnterpriseAdmin;

import com.github.javafaker.Faker;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Business;

import model.Country.Country;
import model.Enterprise.Enterprise;
import model.Org.Organization;
import model.Role.Role;
import model.School.EduData;
import model.School.School;
import model.School.Student;
import model.School.StudentGroup;
import model.UserAccount.UserAccount;

/**
 *
 * @author aprilyz
 */
public class SchoolAdminJPanel extends javax.swing.JPanel {

    Business business = Business.getInstance();
    JPanel workArea;
    UserAccount account;
    School school;
    public Faker FAKER = new Faker();
    
     public static String[] SUPPORTED_COUNTRIES = {"Turkey","Togo","Chile"};
     public static final Map<String, int[]> country2ScoreSetting = new HashMap<String, int[]>() {{
        put("Turkey2015",new int[]{54, 58, 58, 66, 56, 58});
        put("Turkey2016",new int[]{58, 62, 61, 70, 58, 62});
        put("Turkey2017",new int[]{65, 67, 66, 76, 63, 65});
        put("Turkey2018",new int[]{68, 69, 71, 79, 66, 71});
        put("Turkey2019",new int[]{72, 71, 75, 78, 70, 75});
        
        put("Togo2015", new int[]{37, 49, 44, 41, 46, 41});
        put("Togo2016", new int[]{39, 53, 49, 41, 51, 45});
        put("Togo2017", new int[]{41, 55, 55, 44, 52, 50});
        put("Togo2018", new int[]{47, 58, 58, 49, 55, 53});
        put("Togo2019", new int[]{49, 60, 62, 53, 57, 57});
        
        put("Chile2015", new int[]{69, 42, 53, 74, 41, 52});
        put("Chile2016", new int[]{72, 44, 55, 77, 40, 55});
        put("Chile2017", new int[]{68, 40, 54, 75, 36, 51});
        put("Chile2018", new int[]{64, 38, 52, 73, 32, 47});
        put("Chile2019", new int[]{61, 36, 50, 72, 30, 45});
          
    }};
    
    /**
     * Creates new form SchoolAdminJPanel
     */
    public SchoolAdminJPanel(JPanel workArea, UserAccount account) {
        this.workArea = workArea;
        this.account = account;
        this.school = (School)account.getOrganization().getEnterprise();
        initComponents();
        populateComboOrgType();
        lblEnterprise.setText(this.school.getName());
        refreshTable();
    }

    private void populateComboOrgType(){
        for (Organization.OrgType type : Organization.OrgType.values()) {
            if (Enterprise.EtprType.School == Organization.OrgType2EtprType.get(type)){
                typeBox.addItem(type.name());
            }
        }
    }
    
    private void refreshTable(){
        DefaultTableModel model = (DefaultTableModel) tblInfo.getModel();
        model.setRowCount(0);

        for (Organization o : school.orgList) {
            Object row[] = new Object[2];
            row[0] = o;
            row[1] = o.getOrgType().name();
            model.addRow(row);
        }
     }
    
     private void saveInfo(){
      
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblPressure = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lblEnterprise = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblPressure1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        lblTemperature1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Org Type"
            }
        ));
        tblInfo.setEnabled(false);
        jScrollPane1.setViewportView(tblInfo);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Organizations In School");

        lblPressure.setText("Name:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblEnterprise.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblEnterprise.setText("<Enterprise>");

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblPressure1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPressure1.setText("Enterprise:");

        btnUpdate.setText("Unlock/Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background_vertical.png"))); // NOI18N

        lblTemperature1.setText("Type:");

        btnAdd.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(132, 178, 205), 2, true));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPressure)
                                        .addComponent(lblTemperature1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtName)
                                        .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(209, 209, 209)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPressure1)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnterprise)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(bg))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblTitle)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPressure1)
                    .addComponent(lblEnterprise))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblPressure))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature1)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblInfo.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE );
            return;
        }
        Organization selectedRec = (Organization) tblInfo.getValueAt(row, 0);
        business.getOrganizationDirectory().getOrganizationList().remove(selectedRec);
        school.orgList.remove(selectedRec);
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveInfo();

        tblInfo.setEnabled(false);
        btnSave.setEnabled(false);
        btnDelete.setEnabled(false);

        JOptionPane.showMessageDialog(this, "Information saved.", "Information", JOptionPane.INFORMATION_MESSAGE);

        refreshTable();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        tblInfo.setEnabled(true);
        btnSave.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Country country = school.getCountry();
        Organization.OrgType orgType = Organization.getOrgTypeByName(typeBox.getSelectedItem().toString());
        Organization o = business.getOrganizationDirectory().createOrganization(txtName.getText(), country, orgType, school);
        school.orgList.add(o);
        JOptionPane.showMessageDialog(null, "Organization added successfully", "Info", JOptionPane.INFORMATION_MESSAGE);
        refreshTable();
        txtName.setText("");
        
        if (orgType.equals(Organization.OrgType.StudentGroup)) {
            initEduData((StudentGroup)o);
        }
    }//GEN-LAST:event_btnAddActionPerformed


     public void initEduData(StudentGroup studentGroup) {
        if (school.eduDataList.size() < 1 
                && Arrays.stream(SUPPORTED_COUNTRIES).anyMatch(school.getCountry().getName()::equals)) {
            for (int year=2015; year<2020; year++) { //每年15个男生和15个女生
                int[] avgScoreSetting = country2ScoreSetting.get(school.getCountry().getName() + String.valueOf(year));
                int MR = avgScoreSetting[0]; // eg. male reading
                int MM = avgScoreSetting[1];
                int MS = avgScoreSetting[2];
                int FR = avgScoreSetting[3];
                int FM = avgScoreSetting[4];
                int FS = avgScoreSetting[5];
                String name = "";
                for (int i=0; i<15; i++) { // 男
                    name = FAKER.name().firstName();
                     Student student = (Student) Business.getInstance().getUserAccountDirectory()
                            .createUserAccount(name, name, name, Role.RoleType.Student, studentGroup);
                     student.setGender(FAKER.options().option("Male"));
                     studentGroup.username2student.put(student.getUsername(), student);
                     EduData data = new EduData(year, student
                            , FAKER.number().randomDouble(0, MR-10, Math.max(MR+10, 100))
                            , FAKER.number().randomDouble(0, MM-10, Math.max(MM+10, 100))
                            , FAKER.number().randomDouble(0, MS-10, Math.max(MS+10, 100)));
                     school.eduDataList.add(data);
                }
                for (int i=0; i<15; i++) {  // 女
                    name = FAKER.name().firstName();
                    Student student = (Student) Business.getInstance().getUserAccountDirectory()
                            .createUserAccount(name, name, name, Role.RoleType.Student, studentGroup);
                    student.setGender(FAKER.options().option("Female"));
                    studentGroup.username2student.put(student.getUsername(), student);
                    EduData data = new EduData(year, student
                            , FAKER.number().randomDouble(0, FR-10, Math.max(FR+10, 100))
                            , FAKER.number().randomDouble(0, FM-10, Math.max(FM+10, 100))
                            , FAKER.number().randomDouble(0, FS-10, Math.max(FS+10, 100)));
                    school.eduDataList.add(data);
                }
            }
        }
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblPressure;
    private javax.swing.JLabel lblPressure1;
    private javax.swing.JLabel lblTemperature1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblInfo;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> typeBox;
    // End of variables declaration//GEN-END:variables
}
